### ISSUE TITLE
As a beginner, I would like to have a search bar on docs and api pages.

### ISSUE THREAD

**Issue by dineyw23** [rethinkdb/docs#1124] opened 2016-05-16 03:56 UTC
I understand the documentation is static pages and there are alternate ways to search for examples. As a beginner, I refer the docs frequently and have a hard time searching function's example.

**Comment by danielmewes** [comment] 2016-05-16 17:35
Totally agree. We should add this soon.
This is a duplicate of https://github.com/rethinkdb/docs/issues/406 , so I'm closing this one.

**Closed by danielmewes** 2016-05-16 17:35 UTC
