### ISSUE TITLE
set_loop_type documentation missing loop types

### ISSUE THREAD

**Issue by larkost** [rethinkdb/docs#1142] opened 2016-06-20 17:28 UTC
As @bigblind mentioned in rethinkdb/rethinkdb#5870 our documentation does not currently mention that we support `gevent` and `AsyncIO` in our `set_loop_type` documentation.

**Comment by chipotle** [comment] 2016-06-20 17:41
This is essentially a duplicate of long-standing open issues #949 (asyncio) and #1019 (gevent). These are assigned to @Tryneus and they're presumably waiting for him to have enough free cycles to describe this, unless someone else knows enough to do a first draft.

**Comment by danielmewes** [comment] 2016-06-21 01:38
We could go ahead and just add the values `asyncio` and `gevent` to the http://rethinkdb.com/api/python/set_loop_type API document, without providing any real documentation on how to use the driver with these backends.

It's not ideal, but since @Tryneus is still heavily occupied with Horizon-related work, it might be a short improvement for the short term. Going to re-open this with this limited scope.

**Comment by chipotle** [comment] 2016-06-22 18:47
I'm planning on just adding two more bullet points to `set_loop_type` in line with the existing two:

* `"gevent"`: use the [gevent networking library][gev]. Under this model, the connect and run commands will return gevent `AsyncResult` objects.
* `"asyncio"`: use Python 3's [asyncio package][asy]. Under this model, the connect and run commands will return asyncio `Future` objects.

[gev]: http://www.gevent.org
[asy]: https://docs.python.org/3/library/asyncio.html

However, I need to know whether or not that's correct. :) I'm pretty sure from the code that asyncio will return `Future` objects, but I'm not positive about the guidance for gevent. If @larkost or @Tryneus (or somebody else who knows) can chime in, I'll go ahead and make this change.

**Comment by Tryneus** [comment] 2016-06-23 00:16
@chipotle - for `gevent`, it seems we just return the result.  For the most part, it should be indistinguishable from the default Python driver once you're inside your event loop.  The `AsyncResult` object is just used internally.

**Closed** 2016-06-23 22:24 UTC
