### ISSUE TITLE
why does exhausting the cursor throw an error?

### ISSUE THREAD

**Issue by jonathanong** [rethinkdb/docs#623] opened 2015-01-19 20:08 UTC
https://github.com/rethinkdb/rethinkdb/issues/3601#issuecomment-70552201

why not just return null? now i have to check for errors when all i want to know is that there are no more documents

**Comment by danielmewes** [comment] 2015-01-19 20:14
Returning `null` might be problematic if the query returns `null` as a result, e.g. `r.table(...).map(function(x) { return null; })`

**Comment by jonathanong** [comment] 2015-01-19 20:17
that looks like an issue with the developer, not the driver.

**Comment by danielmewes** [comment] 2015-01-19 21:01
@jonathanong Can you explain that a bit more?
The problem is that with `null` you couldn't distinguish a query returning `null` (but potentially having more results) from the cursor being exhausted.

**Comment by jonathanong** [comment] 2015-01-19 22:47
if a document itself is `null`, then that doesn't make sense at all and i would consider that a developer error.

if a query returns nothing, then `.next() -> null` is expected behavior, which makes sense.

**Comment by chipotle** [comment] 2015-01-19 23:09
Queries don't always return documents, though. It might return just the value of a field:

```js
r = require('rethinkdb');

r.connect({host: 'localhost', port: 28015}, function (err, conn) {
	if (err) throw err;

	r.table('foo')('name').run(conn, function (err, cursor) {
		if (err) throw err;
		var fetchNext = function (err, res) {
			if (err) {
				console.log(err.message);
			} else {
				console.log(res);
				cursor.next(fetchNext);
			}
		}
		cursor.next(fetchNext);
	});
});
```

If one of the fields you iterated through actually had a `null` value in it, you'd want to be able to distinguish that from "this field had an actual `null` in it" and "we have no more rows in the cursor."

**Comment by danielmewes** [comment] 2015-01-19 23:11
I'm going to close this because it doesn't belong in the docs repo, and we cannot change it to `null` for the reasons pointed out.
Please feel free to re-open in https://github.com/rethinkdb/rethinkdb/issues/ if you think we could find a better interface for passing on the information that a cursor has been exhausted.

**Closed by danielmewes** 2015-01-19 23:11 UTC

**Comment by danielmewes** [comment] 2015-01-19 23:12
(another example is something like this pseudo-join `r.table('t1').map(r.table('t2').get(r.row('foreign_key')))` )

**Comment by jonathanong** [comment] 2015-01-19 23:21
ok np. as long as you guys implement a readable stream, i wouldn't need to use `.next()` directly anyways
