### ISSUE TITLE
Add list of strings typeOf() returns

### ISSUE THREAD

**Issue by jimoe** [rethinkdb/docs#996] opened 2016-01-11 07:11 UTC
On 'https://rethinkdb.com/api/javascript/type_of/' I suggest you add a list of the exact string typeOf(() returns for each type.  Or a link to a  page where you can find that information.

**Comment by chipotle** [comment] 2016-01-11 07:51
I'm closing this as a duplicate of #994, which is for doing both of your suggestions (the list of strings `typeOf` returns and a link to the data types document). This is definitely a good idea and coming shortly. :)

**Closed by chipotle** 2016-01-11 07:51 UTC
Labels: duplicate
